### ISSUE TITLE
Related project

### ISSUE THREAD

**Issue by rslruiz** [binisya/sl3-WWoman-Project#2]
Differentiate your project from this one <https://www.mathworks.com/matlabcentral/fileexchange/26367-guitar-tuner>.

**Comment by bettinadayrit** [comment]
Good day sir! This was from the initial project proposal submission— the group acknowledged your comment po and revised the proposal as follows in the final project proposal submitted in the repository files. However, this is still noted on our end and will be updating the README file based on the final proposal. Thank you sir!
